--- #YAML:1.0
name:                WWW-Crawler
version:             0.001
abstract:            A threaded crawler/spider for the web.
license:             ~
author:              
    - John Drago <jdrago_999@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
test_requires:
    Test::More:             0
requires:
    HTML::LinkExtor:        3.60
    threads:                1.77
    LWP::UserAgent:         5.834
    HTTP::Request::Common:  5.824
    POSIX:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
